# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:    true
            anonymous:    true
            oauth:
                failure_path: your_path
                login_path: your_path
                check_path: /connect_check
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                oauth_user_provider:
                    service: app.provider.oauth
              
        # secured_area:
        #     anonymous: ~
        #     oauth:
        #         resource_owners:
        #             facebook:           "/login/check-facebook"
        #             google:             "/login/check-google"
        #             my_custom_provider: "/login/check-custom"
        #             my_github:          "/login/check-github"
        #         login_path:        /login
        #         use_forward:       false
        #         failure_path:      /login

        #         oauth_user_provider:
        #             service: hwi_oauth.user.provider.fosub_bridge


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
